version: "3"
services:
  xxxxx-rabbit-mq:
    container_name: xxx-rmq
    privileged: yes
    network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/jetson-inference
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/video0:/dev/video0
    environment:
      - DISPLAY
    tty: true

